import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: 'Buteco Pé de Serra - Gerador de Templates HTML',
  description: 'Generated by Firebase Studio',
  icons: {
    icon: 'https://raw.githubusercontent.com/riquelima/BlueGeradordeTemplates/refs/heads/master/3-Transparent.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;700&family=Lilita+One&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased">
        <div className="bg-blurs"></div>
        <main className="relative z-10">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
